import mongoose from 'mongoose';

const tripSchema = new mongoose.Schema({
  tripId: {
    type: String,
    unique: true,
    required: true  // Generated by pre-validate middleware
  },
  // Trip details
  riderName: {
    type: String,
    required: true,
    trim: true
  },
  riderPhone: {
    type: String,
    trim: true
  },
  riderEmail: {
    type: String,
    trim: true,
    lowercase: true
  },
  
  // Locations
  pickupLocation: {
    address: { type: String, required: true },
    lat: { type: Number, required: true },
    lng: { type: Number, required: true },
    notes: String
  },
  dropoffLocation: {
    address: { type: String, required: true },
    lat: { type: Number, required: true },
    lng: { type: Number, required: true },
    notes: String
  },
  
  // Scheduling
  scheduledDate: {
    type: Date,
    required: true
  },
  scheduledTime: {
    type: String,
    required: true
  },
  estimatedDuration: {
    type: Number // in minutes
  },
  estimatedDistance: {
    type: Number // in kilometers
  },
  
  // Assignment
  assignedDriver: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  
  // Status tracking
  status: {
    type: String,
    enum: ['pending', 'assigned', 'in_progress', 'completed', 'cancelled'],
    default: 'pending'
  },
  
  // Time tracking
  actualPickupTime: Date,
  actualDropoffTime: Date,
  
  // Additional information
  tripType: {
    type: String,
    enum: ['regular', 'medical', 'urgent', 'recurring'],
    default: 'regular'
  },
  specialInstructions: String,
  
  // Recurring trip information
  isRecurring: {
    type: Boolean,
    default: false
  },
  recurringPattern: {
    frequency: {
      type: String,
      enum: ['daily', 'weekly', 'biweekly', 'monthly', 'custom']
    },
    daysOfWeek: [Number], // 0-6 (Sunday-Saturday)
    weekOfMonth: Number, // 1-4 for specific week of month
    interval: Number, // Every N days/weeks/months
    endDate: Date,
    endAfterOccurrences: Number, // Alternative to endDate
    isIndefinite: {
      type: Boolean,
      default: false
    },
    customPattern: String // For complex patterns like "every other Tuesday"
  },
  parentTripId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Trip'
  },
  childTripIds: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Trip'
  }],
  
  // Driver updates
  driverNotes: String,
  driverLocation: {
    lat: Number,
    lng: Number,
    lastUpdated: Date
  },
  
  // Rating and feedback
  rating: {
    type: Number,
    min: 1,
    max: 5
  },
  feedback: String,
  
  // Cost information
  estimatedCost: Number,
  actualCost: Number,
  
  // Cancellation
  cancellationReason: String,
  cancelledBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  cancelledAt: Date
}, {
  timestamps: true
});

// Generate unique 8-character trip ID before validation
tripSchema.pre('validate', function(next) {
  if (!this.tripId) {
    // Generate 8-character alphanumeric ID
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let tripId = '';
    for (let i = 0; i < 8; i++) {
      tripId += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    this.tripId = tripId;
  }
  next();
});

// Index for efficient queries
tripSchema.index({ assignedDriver: 1, status: 1 });
tripSchema.index({ scheduledDate: 1 });
tripSchema.index({ createdBy: 1 });
// tripId index created automatically by unique: true

export default mongoose.model('Trip', tripSchema);